version: '3.9'

networks:
  app-net:
    driver: bridge

services:
  mongodb_sdc:
    image: mongodb_product_service
    ports:
      - "27017:27017"
    networks:
      - app-net

  api:
    build: .
    depends_on:
      - mongodb_sdc
    ports:
      - "5000:5000"
    networks:
      - app-net
    links:
      - mongodb_sdc